#! /usr/bin/env bash

set -e

for bin in "cargo" "mktemp" "zellij"; do
    if ! command -v $bin &> /dev/null; then
        echo >&2 "\`$bin\` not found"
        exit 1
    fi
done
for cmd in "add" "watch"; do
    if ! cargo help "$cmd" &> /dev/null; then
        echo >&2 "\`cargo $cmd\` not found"
        exit 1
    fi
done

root_dir="$(mktemp --directory --tmpdir rustp-XXXXXX)"

mkdir -p "$root_dir"
cargo init "$root_dir"
cd $root_dir

if [ $# -gt 0 ]; then
    cargo add "$@"
fi

# See `zellij/layouts/rustp.kdl`.
if [ -n "$ZELLIJ" ]; then
    zellij action new-tab --layout rustp
else
    zellij --session rustp --layout rustp
fi
